# Generated by Django 5.2.6 on 2025-09-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitlog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Как часто вы хотите выполнять в период'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_datetype',
            field=models.CharField(choices=[('every_day', 'Каждый день'), ('week', 'Кол-во раз в неделю')], default='every_day', verbose_name='Как вы хотите выполнять привычку?'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='purpose',
            field=models.CharField(blank=True, max_length=150, verbose_name='Смысл привычки для вас'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
