# Generated by Django 5.2.6 on 2025-09-05 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habitlog_options_alter_habit_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)], verbose_name='Сколько раз в неделю вы хотите выполнять привычку'),
        ),
    ]
