# Generated by Django 5.2.6 on 2025-09-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=1, verbose_name='Сколько раз в неделю вы хотите выполнять привычку'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='purpose',
            field=models.CharField(blank=True, max_length=150, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
