# Generated by Django 5.2.6 on 2025-09-05 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_frequency_alter_habit_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=datetime.date(2025, 9, 5)),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='status',
            field=models.CharField(choices=[('complited', 'Выполнено'), ('incomplited', 'Не выполнено'), ('forgot', 'Забыл записать!!')]),
        ),
    ]
