# Generated by Django 5.2.6 on 2025-09-07 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habitlog_date_alter_habitlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='status',
            field=models.CharField(choices=[('complited', 'Выполнено'), ('incomplited', 'Не выполнено'), ('forgot', 'Не записано!')]),
        ),
    ]
