# Generated by Django 5.2.6 on 2025-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habitlog_date_alter_habitlog_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitlog',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='habit_datetype',
        ),
        migrations.AddField(
            model_name='habit',
            name='datetype',
            field=models.CharField(choices=[('weekly', 'Кол-во раз в неделю'), ('daily', 'Каждый день')], default='weekly', verbose_name='Как вы хотите выполнять привычку?'),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='status',
            field=models.CharField(choices=[('complited', 'Выполнено'), ('incomplited', 'Не выполнено'), ('forgot_to_mark', 'Забыли записать!')]),
        ),
    ]
