# Generated by Django 5.2.6 on 2025-09-20 21:32

import habits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_habitlog_options_remove_habit_habit_datetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=habits.models.get_local_now_date),
        ),
    ]
